# Project information
terra.description=A modern voxel world generation platform (SkyXNetwork fork for Paper 26.1.2)
terra.source=https://github.com/XPaladiumyX/Terra
terra.issues=https://github.com/XPaladiumyX/Terra/issues
terra.wiki=https://github.com/PolyhedralDev/Terra/wiki
terra.license=MIT
# Gradle options
org.gradle.jvmargs=-Xmx4096M -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8
org.gradle.warning.mode=all

